### ISSUE TITLE
Set Terms Of Use  (API endpoint #7)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#110]
**Input**: OpenDPUserID, TermsOfUseID

**Output**: ```{"success": true/false}```

**Notes**
Do we need to specify that user accepts or rejects? Or is rejecting the same as not recording an acceptance? Change TOS based on the installation

**Logging**
For audit trail, record a rejection.

**Reference**: https://docs.google.com/spreadsheets/d/1FcxCMqP6z0PUN-5cIEcpxbqlNamuL9oq_73D32ON9E8/edit#gid=0

**Comment by ekraffmiller** [comment]
The client side code for this is part of https://github.com/opendp/dpcreator/pull/242
