### ISSUE TITLE
DepositorSetupInfo "Patch" endpoint

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#187]
### Inputs
- object_id of DepositorSetupInfo
- field name(s)/data
  - Most common case will be:
    - Data field (e.g. `dataset_questions`) 
    - Updated status for `user_step`
  
### Example, DepositorSetupInfo, error

```json
{
   "object_id":"9e7e5506-dd1a-4979-a2c1-ec6e59e4769c",
   "dataset_questions":{
      "question_1":true
   },
   "user_step":"error_9100"
}
```

**Comment by ecowan** [comment]
This is actually already supported, the only thing we may need to change is which fields can and cannot be modified via patch. 

For example, using the UI, we can go to http://localhost:8000/api/deposit/9255c067-e435-43bd-8af1-33a6987ffc9b/ and use the "raw data" form at the bottom to make patch updates.

**Comment by raprasad** [comment]
Fields that are "patchable":
- `user_step`
- `dataset_questions`
- `variable_ranges`
- `variable_categories`
