### ISSUE TITLE
django basic setup

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#19]
- authentication
- `backend` directory

- Combined with #18, use this setup for now: https://github.com/EugeneDae/django-vue-cli-webpack-demo

**Comment by mikephelan** [comment]
This setup, based on an alternative means of rendering Django content via Vue without actually writing Vue templates, can be found under branch, django-vue-cli-webpack. One concern is that a preference for material design expressed by @tercer and others may not be satisfied as well by django-vue-cli-webpack as it might be directly in Vue by a a Vue UI library such as [Vuetify](https://vuetifyjs.com/en/).

**Comment by mikephelan** [comment]
See the README.md under branch django-vue-cli-webpack for setup and run instructions.
