### ISSUE TITLE
update/improve cypress tests

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#197]
- management command for cypress tests
   - refresh db between commands
   - keep only user, registered DV fixtures
   - use env variable for cypress tests

**Comment by ShubhamPalriwala** [comment]
Hey @raprasad, Are we looking to test only frontend components as of now?

**Comment by raprasad** [comment]
@ShubhamPalriwala Thanks for the note. Are you interested in helping with this project?

**Comment by ShubhamPalriwala** [comment]
Yeah definitely !

**Comment by ShubhamPalriwala** [comment]
Hey @raprasad are you working on it since you've moved it to `In Progress`?
