### ISSUE TITLE
both fileId and filePid are required for Dataverse Handoff

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#217]
Currently, both fileId and filePid are required when creating a DataverseHandoff object.  But only one of these fields is needed, either fileId or Pid, to identify the file.  Do we need to require both fields in the API, or should we make it valid to pass just fileId or Pid?

**Comment by pdurbin** [comment]
If it helps, all Dataverse installations support fileId (database ID). Only some Dataverse installations support filePid (DOI, usually), which is controlled by a system-wide setting.

**Comment by ekraffmiller** [comment]
Based on Phil's comments, it makes sense to keep things as they are - requiring fileId.  I think it's ok to close this.
