### ISSUE TITLE
UI refinements

### ISSUE THREAD

**Issue by TaniaSchlatter** [opendifferentialprivacy/opendp-ux#218]
This issue is to list and track refinements to the Open DP Creator UI, in rough order of priority:

- [ ] address restricted mobile functionality and messaging (ux & ui) #163
- [x] move the message on the "Validate Dataset" to the "Confirm Variables" page. TBD: change the style to be more of a call to action, and less of a warning. 
- [ ] determine if help should be dismissible, and/or how to get it back if closed ("Set epsilon value" page) 
- [ ] homepage "Tips" [need refinement](https://miro.com/app/board/o9J_l9OsJSc=/?moveToWidget=3074457361596843868&cot=10)/user feedback.

**Comment by TaniaSchlatter** [comment]
Efforts related to completing text for the app are tracked in a separate issue: #89

**Comment by ekraffmiller** [comment]
removed items that don't require further discussion to #250

**Comment by raprasad** [comment]
closing, covered in other issues
