### ISSUE TITLE
small UI changes

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#250]
Taken from Issue #218 , these are items that don't require further discussion.  Details are on the Miro board
https://miro.com/app/board/o9J_l9OsJSc=/?moveToWidget=3074457361594291288&cot=14

 - [x] add logo file to the UI – Miro mockup.
- [ ]  move the "To create a DP Release, please make a request from a registered Dataverse installation." to the descriptive text – Miro mockup. (See Miro board yellow stickie suggestion)
- [ ]  de-emphasize "time remaining" in the UI – put it under the "Continue" button – Miro mockup

**Comment by TaniaSchlatter** [comment]
[Folder with .svg logo to use for OpenDP Creator](https://drive.google.com/drive/folders/1TiGcDuMquV5Gt_GjbkWplR17YrRyVmD0?usp=sharing)
![DPCreator_from_OpenDP](https://user-images.githubusercontent.com/15386424/128087193-f6a7c370-ce88-40e5-83bc-86adff8ac19e.gif)

**Comment by raprasad** [comment]
Thanks @TaniaSchlatter
