### ISSUE TITLE
Allow the user to edit variable types

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#265]
- depends on #350 
---

- The confirm variables page classifies variables as numeric, categorical, or boolean.
 - However, for numerics, it needs to further distinguish between floats and ints
 - This is not available via the current profiler, e.g. user input is needed
 - Can the profiler give the reason for determining categorical, etc?
 - What if the user makes an incorrect choice? 
   - What are the implications?

**Comment by raprasad** [comment]
- Currently, the TwoRavens profiler determines the variable type—the “**Type**” column.
- For the new OpenDP library, columns of type “Numerical” need to further specified as “integer” or “float”
- We have 3 possible ways to do this:

---

1. Modify the profiler to make a (somewhat naive) distinction between “integer” and “float”
2. Ask for user input—allow the user to directly set the type.
3. Default to the profiler’s value and optionally let the user directly set the type.

---
- Question 1: Which, if any, is the best choice ^ from a DP integrity perspective? Note: these changes can only be made by a depositor/trusted curator; not an analyst.
- Question 2: Should we allow the user to modify all variable types? (Earlier we had attempted to make the UI “easier” by removing that option.)
- Question 3: What are the expectations regarding the depositor/trusted curator’s knowledge of the feature types? Is it expected that they will know the data and potentially have access to the code book?
- Question 4: Is having (A) the ability to modify types and (B)  the entry boxes for categories/ranges on the same page incongruous?  (e.g. We do want the exact types but we don’t want the user referencing any material, including the dataset, for categories/ranges.)

**Comment by ekraffmiller** [comment]
One other aspect of this issue - the profiler is returning type Numeric for some variables that are actually Categorical (for example, if all the categories are integers)

**Comment by raprasad** [comment]
moved to #379
