### ISSUE TITLE
Logic for Statistic Validation/Release

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#275]
### "Validation" step w/o data

- Input: 
   - (1) `dp_statistics` (JSON structure)
      - array of objects
         - each object describes one stat
            - type of stat
            - feature/column name
            - epsilon
            - how to handle missing values
   - (2) AnalysisPlan `object_id` 
      - Used to retrieve an AnalysisPlan from the database in order to retrieve  `variable_info`
          - `variable_info` contains the data type of the column and min/max, categories, etc.      
- Iterate through all the stats sent over and validate them
    - Using the `dp_statistics` structure, add the following fields for each statistic
       - `validated` field for each statistic. Did the stat validate?
          - ^ related error message if invalid
       - `error/accuracy` measure (if/when available through the OpenDP lib)

----

## Potential approach

- Logic layer that makes use of `dp_statistics` and `variable_info` data to iterate through the statistics and either validate or calculate all of them 
- Separate classes for each statistic type with a common interface (mean, histogram, count, sum, variance)
   - constructor - takes in the statistic specification, and, optionally, the data source
   - `.is_valid()` - method that chains together the preprocessor steps but doesn't touch the data
      - When available, is potentially combined with another step to calculate accuracy
   - `.make_release()` - attempts to compute the statistic; again checking validity
      - This method touches the data and results in epsilon cost, etc.
   - These classes can be used/tested outside of the API endpoints

**Comment by ekraffmiller** [comment]
Here is sample JSON related to the endpoint, which is saved in the AnalysisPlan model - 

**- dp_statistics (also sent as a parameter for validation):**

[
    {
        "error": "",
        "label": "EyeHeight",
        "locked": false,
        "epsilon": 0.0625,
        "variable": "eyeHeight",
        "statistic": "Mean",
        "fixed_value": "5",
        "handle_as_fixed": true,
        "missing_values_handling": "Insert fixed value"
    },
    {
        "error": "",
        "label": "TypingSpeed",
        "locked": false,
        "epsilon": 0.0625,
        "variable": "typingSpeed",
        "statistic": "Mean",
        "fixed_value": "0",
        "handle_as_fixed": false,
        "missing_values_handling": "Insert random value"
    },
    {
        "error": "",
        "label": "CorrectedError",
        "locked": false,
        "epsilon": 0.0625,
        "variable": "correctedError",
        "statistic": "Histogram",
        "fixed_value": "0",
        "handle_as_fixed": false,
        "missing_values_handling": "Insert random value"
    },
    {
        "error": "",
        "label": "Trial",
        "locked": false,
        "epsilon": 0.0625,
        "variable": "trial",
        "statistic": "Histogram",
        "fixed_value": "0",
        "handle_as_fixed": false,
        "missing_values_handling": "Drop them"
    }
]

**- variable_info** 
{
    "trial": {
        "name": "Trial",
        "type": "Categorical",
        "label": "Trial",
        "categories": [
            "cat1",
            "cat2",
            "cat3"
        ]
    },
  
    "eye_height": {
        "max": 10,
        "min": 1,
        "name": "EyeHeight",
        "type": "Numerical",
        "label": "EyeHeight"
    },
    "typing_speed": {
        "max": 20,
        "min": 10,
        "name": "TypingSpeed",
        "type": "Numerical",
        "label": "TypingSpeed"
    },
 
    "corrected_error": {
        "max": 100,
        "min": 0,
        "name": "CorrectedError",
        "type": "Numerical",
        "label": "CorrectedError"
    }
  
  
 

}

**Comment by raprasad** [comment]
- [ ] update to opendp==0.2.1 and add accuracy to the validation step
- [ ] use the profiler to guess at float/int for numeric
  - [ ] (if time), allow user to change variable types
