### ISSUE TITLE
PUMS demo dataset

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#308]
- Data: https://github.com/opendp/PSI/blob/develop/data/PUMS5extract10000.csv
   - ^ This has 10k rows, we'll use a bigger format, same file for the demo
- Metadata: https://www.census.gov/data/datasets/2000/dec/microdata.html
- [x] Add to mock dataverse
- [x] Need to add descriptive metadata and deposit into Dataverse

**Comment by pdurbin** [comment]
I made this pull request yesterday to add PUMS to the Dataverse sample data repo: https://github.com/IQSS/dataverse-sample-data/pull/28

I also set up the same on the test server.
