### ISSUE TITLE
Error handling in Spec

### ISSUE THREAD

**Issue by ecowan** [opendifferentialprivacy/opendp-ux#337]
Error messages should contain more context. For example, if None is passed where a list is expected, the message will simply say that it can't iterate over a None type, without specifying which value is the culprit. We may be better off providing the stacktrace as well.

**Comment by raprasad** [comment]
(copied from slack for reference)

here’s some stuff going on…needs documention
e.g. If the data needs to be evaluated on init:

1. add the property to `additional_required_props`
    - https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/stat_spec.py#L106
2. make sure the property has the correct validator here:
    - https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/stat_spec.py#L40

---

Alternately, put checks in:
1. **pre**:  happen before the “canned” validation above https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/stat_spec.py#L115
2. **post**: happen right after the “canned” validation: https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/tools/stat_spec.py#L133

**Comment by raprasad** [comment]
closing. specific error above is covered and many error messages have been added since
