### ISSUE TITLE
design: can the wrappers for dp functions be added to OpenDP contrib?

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#347]
- Can we "generify" the wrapper classes to be a separate module or added to OpenDP contrib.
- e.g. If you want to make a DP Mean using float values, you can use a "canned" preprocessor in a wrapper class

**Comment by Shoeboxam** [comment]
I have some ideas on this (these are ideas, not requests!). I think a `make_measurement_from_json` function that accepts json and returns a plain old core-lib measurement would be a really useful abstraction. The json provides us with a serialization format for computation pipelines and the interface matches the core library. 

Using the above constructor, I think these wrapper classes could just be glorified json manipulators? When you do something that actually requires a core library measurement (like invoking the function), you materialize the measurement by invoking the `make_measurement_from_json` constructor. This way the classes themselves remain pickle-able and serializable.

That being said, if the frontend already crafts json in the relevant format, then you might be able to skip writing wrapper classes altogether. It is nice to bundle accuracy estimates with the class interface, but wrappers will need some unintuitive unwrapping or maybe a mixin to work with the core lib combinators.

**Comment by raprasad** [comment]
Closing. Will be covered by https://github.com/opendp/opendp/milestone/12
