### ISSUE TITLE
allow users to add min/max or categories later in the wizard

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#352]
If users select a statistic in the Add Statistics Dialog for which variables have not been confirmed (adding min/max, category type), allow them to do that and continue with the release.

**Comment by ekraffmiller** [comment]
Reviewed with Tania, and we decided to handle the missing data by providing a link back to the confirm variables page, and and create a separate ticket for improving the user experience, post November release.

**Comment by ekraffmiller** [comment]
Link to separate ticket: #357

**Comment by raprasad** [comment]
Note: the backend update for this is in PR #364

**Comment by raprasad** [comment]
no longer applies. depositor chooses variables and is compelled to add any required info (min/max, categories, bool vals, etc)
