### ISSUE TITLE
Print statements in tests

### ISSUE THREAD

**Issue by ecowan** [opendifferentialprivacy/opendp-ux#366]
In test_dp_histogram_spec we have calls of the form:

```print('\nUI info:', json.dumps(dp_hist.get_error_msg_dict()))```

for certain chaining errors, we end up with an OpenDPException which is not JSON serializable. We need to make sure that we are catching all error types (even ones we never expect to see in production) so we can parse them properly.

**Comment by raprasad** [comment]
fixed with logging
