### ISSUE TITLE
DepositorSetupInfo last updated field isn't updated

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#372]
When calling PATCH on DepositorSetupInfo, the updated field in the object is no longer being updated. Could this have to do with the changes to updateDepositorSetupInfo() fix the race condition?

**Comment by raprasad** [comment]
- potential place to add update: https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/dataset/serializers.py#L107
