### ISSUE TITLE
Allow the user to edit variable types

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#379]
On the confirm variables page, allow the user to choose the variable types, with choices being:

- 'Boolean'
- 'Categorical'
- 'Integer'
- 'Float'

Note: 'Numerical' is removed and replaced with Integer/Float

(related to #350, replaces #265)

**Comment by ekraffmiller** [comment]
How do we want to handle the relationship between the dropdown and the additional info options in the table?  For example, if a user has already entered a max and min, should we allow them to change the type to something that isn't numeric?  If we allow, should we force the user to undo the additional info, do it automatically, or maybe have a "clear" link next to the additional info? 
I think clearing automatically is probably the best from the user prospective (that way we aren't "locking" the dropdown if the additional info is there - I think that would be confusing for the user), but want to see what others think.

**Comment by ekraffmiller** [comment]
I reviewed this with Tania and she recommended showing a message above the dropdown when the user clicks into it, that warns user that the additional info will be cleared if its not appropriate to the new type (the message will only appear when the user goes to edit a type that already has additional info entered).
