### ISSUE TITLE
Sample releases (sparse and more complete) for Dataverse explore

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#39]
Prepare sample DP DDI XML files for Dataverse to use for a DP Explore tool.

e.g. Start with two sample files, one sparse and one full
  - for full: populate DDI using quintile stats and post process estimates which will give almost everything on the DDI 

---

- [ ] 1. Generate two PUMS releases from whitenoise core
  - [x] "sparse" release
  - [x] full release
- [ ] 2. Adjust JSON schema to conform with these releases.  (Schema needs to be more extensible)
  - [ ] Current schema work is here:  https://github.com/opendifferentialprivacy/OpenDP-Experimental/tree/master/release_schemas
    - See README ^ as well as brief note in the [test_schemas.py file](https://github.com/opendifferentialprivacy/OpenDP-Experimental/blob/master/release_schemas/test_schemas.py)
  - [ ] update python script to validate the schemas.  See 
- [ ] 3. Convert the JSON to DDI format
  - (@scolapasta is a good resource for references)

**Comment by mikephelan** [comment]
Generation of PUMS releases uncovered a bug in the Analysis.report() functionality. The report() always comes back as an empty list. It will be fixed in whitenoise-core 0.3.

**Comment by mikephelan** [comment]
Analysis.report() functionality bug has a workaround in branch [ms-cites](https://github.com/opendifferentialprivacy/whitenoise-core/tree/ms-cites).

**Comment by mikephelan** [comment]
sparse release:
`[{'description': 'DP release information', 'variables': 'age', 'statistic': 'DPMean', 'releaseInfo': 44.83344766055165, 'privacyLoss': {'delta': 0.0, 'epsilon': 0.65, 'name': 'approximate'}, 'accuracy': None, 'submission': 0, 'nodeID': 11, 'postprocess': False, 'algorithmInfo': {'mechanism': 'Automatic', 'name': '', 'cite': '', 'argument': {'constraint': {'lowerbound': 0.0, 'upperbound': 100.0}, 'implementation': 'resize', 'n': 1000}}}]`

**Comment by mikephelan** [comment]
full release:
`[{'description': 'DP release information', 'variables': 'income', 'statistic': 'DPMaximum', 'releaseInfo': 2743921.2338242335, 'privacyLoss': {'delta': 0.0, 'epsilon': 0.65, 'name': 'approximate'}, 'accuracy': None, 'submission': 0, 'nodeID': 21, 'postprocess': False, 'algorithmInfo': {'mechanism': 'Automatic', 'name': '', 'cite': '', 'argument': {'constraint': {'lowerbound': 0.0, 'upperbound': 1000000.0}}}}, {'description': 'DP release information', 'variables': 'age', 'statistic': 'DPMean', 'releaseInfo': 45.52654758068556, 'privacyLoss': {'delta': 0.0, 'epsilon': 0.65, 'name': 'approximate'}, 'accuracy': None, 'submission': 0, 'nodeID': 11, 'postprocess': False, 'algorithmInfo': {'mechanism': 'Automatic', 'name': '', 'cite': '', 'argument': {'constraint': {'lowerbound': 0.0, 'upperbound': 100.0}, 'implementation': 'resize', 'n': 1000}}}]`

**Comment by mikephelan** [comment]
We successfully ran the schema on the instance, both in Python and via CLI. Instance is producing some invalid JSON, including Python keywords rather than Javascript keywords, and missing keys. Appears that produced instance will need to be modified before the schema is altered to validate the instance.
