### ISSUE TITLE
Error when retrieving dataverse file info for restricted file

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#407]
For the Dataverse use case, the POST to dv-file is failing when the file is restricted.  The response: 400. Message: "success":false,"message":"Info for file not found in the schema. Did not find fileId \"15\"" .

**Comment by ekraffmiller** [comment]
Need to compose the download URL directly, rather than getting it from the export metadata API (because the export API doesn't include the download URL for restricted files.
Example of the download URL: 
"http://ec2-18-232-125-211.compute-1.amazonaws.com/api/access/datafile/<file id>"

**Comment by raprasad** [comment]
closing. this will change with signed urls #127
