### ISSUE TITLE
User Demo OpenDP app and instructions

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#410]
To do as of 3/28

- [x] update screenshots
- [x] link the "quickstart" and "tutorial" to the banner

**Comment by anniewu332** [comment]
Draft with screenshots done.

**Comment by TaniaSchlatter** [comment]
Is [this the instructions doc](https://docs.google.com/document/d/1cjogg37M069Y5JwOJ5FC6w_BAqhyUmgag6eXXpJmegA/edit?pli=1)? 
I assume it is what we want to test with Harvard Dataverse curators. 
Definition of done is instructions that are clear to Harvard Dataverse curators and a few other representative users?

**Comment by anniewu332** [comment]
@TaniaSchlatter Yes that is the instructions doc in draft.  Some of the screenshots will need to be updated after we finalize the text for user testing (e.g. by Harvard Dataverse curators team).  The instructions will have to be clear at least to the Harvard Dataverse curators.  If we could have some users new to Dataverse to approve the instructions that will be perfect.

**Comment by raprasad** [comment]
For instructions
- [ ] Initial access. Google Doc, read-only via an opendp.org account
- [ ] Google drive that's public
- [ ] Links to test files to upload
---
Prior to Harvard Curation team review
- [ ] Ask Andy and Mike to go through the app
- [ ] Address logistics: scope of review: do we want people to create accounts? (Yes) Define one or more data files for participants to use (more if releases are not "cleaned out")

**Comment by TaniaSchlatter** [comment]
Here is a [document that outlines plans for getting feedback](https://docs.google.com/document/d/1Vej9gi08ti_8ewQlFDp2gcBC3rRc3XnplxLyVizt5sM/edit?usp=sharing)
