### ISSUE TITLE
Change Deposit API call: add `Content-type` to the header

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#431]
!**Note**: Depends on  Dataverse issue: https://github.com/IQSS/dataverse/issues/8241, the syntax of the API call may change--and will be reflected in the DV docs
   - finalized 12/8, see: https://github.com/IQSS/dataverse/issues/8241#issuecomment-988812491
---

- [ ] change upload type, ("DpJSON"? so it ends up in the correct Dataverse download category?)

For depositing auxiliary files, add `Content-type` to the header with the type of the file being deposited.

This is to fix the problem where JSON files weren't being detected.

```
curl -H X-Dataverse-key:$API_TOKEN -X POST -H "Content-type:application/json" $SERVER_URL/api/dataverses/$ID/roles --upload-file roles.json
```

**Comment by pdurbin** [comment]
We ended up going with the solution at https://github.com/IQSS/dataverse/pull/8282 where `type` is sent with the file like this (curl example):

```
export FILENAME='auxfile.json'
export FILETYPE='application/json'

curl ... -F "file=@$FILENAME;type=$FILETYPE"
```

Here's a screenshot of the updated docs from Dataverse 5.9, which has this fix:

<img width="884" alt="Screen Shot 2021-12-10 at 11 22 34 AM" src="https://user-images.githubusercontent.com/21006/145606934-d820280c-fe9b-4fd5-87c0-87bbbe45cdab.png">

From https://guides.dataverse.org/en/5.9/developers/aux-file-support.html

You are welcome to test at https://demo.dataverse.org where Dataverse 5.9 has been deployed.
