### ISSUE TITLE
Profiler on Boolean Type

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#433]
I noticed something about the profiler in testing the demo DP Creator today.  Out of the three boolean columns in the test data file I used (http://ec2-35-171-244-178.compute-1.amazonaws.com/dataset.xhtml?persistentId=doi:10.5072/FK2/V6YFKL&version=1.0), the first one (Boolean1) didn’t have any missing value, while the other two (Boolean2 and Boolean3) had missing values.  The profiler recognized the first one as boolean and the other two as categorical.  Is this expected behavior?

**Comment by raprasad** [comment]
Currently: 2-valued variables are Boolean by assumption after profiling, and then the user checks/overrides that if incorrect.

**Comment by raprasad** [comment]
Being handled in #591
