### ISSUE TITLE
Changes to Create Statistic Popup

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#437]
From #419:
- Miro reference: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366776975026&cot=14
- “Which variable would you like to use?”
	- [ ] Only show variables selected on the **Confirm Variables** page.
	- [ ] Allow selection of only one variable at a time
	- [ ] Add text: “Would you like to add another variable?” or similar		
		* Link text back to the “Confirm Variables” page
		- workflow for later: Add shortcut from “Confirm Variables” page back to “Create the statistics” page,
- "How would you like missing values to be handled?”
	- [ ] Remove “Insert random value”
- Debug checks
	- [ ] Make sure editing works as well as selecting variables, etc.
	- [ ] What happens if a statistic is created with “EyeHeight” but the user goes back to Confirm Variables and de-selects “EyeHeight”, etc.

**Comment by raprasad** [comment]
- [x] send list of stats and available var types (@raprasad)

**Comment by raprasad** [comment]
- [ ] For "Enter fixed value", do not have a default value or change default depending on data type
  - Current default is `0` (zero) but shouldn't be if variable is categorical, etc.
  - (Ideal, if possible given the time): Display the variable's min/max or categories under the fixed value box
