### ISSUE TITLE
Validate Dataset Text Changes

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#455]
- Miro reference: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366777335859&cot=14
- [x] Change text  “Used **dataset**: Replication …..” to “Used **data file**”. [boldface only added to emphasize change, e.g. don’t use boldface]
- [x] Initial sentence, remove “Firstly, we need to”, start with “Confirm…”
- [x] Remove warning box that reads “You must complete this questionnaire…”
- Question: Which of the following best describes your dataset
	- 1st Choice: “Public Information”
		- [x] Add additional sentence about how DP isn’t needed
	- Last Choice: “Information that would cause sever harm…”
		- [x] Add additional sentence about how application not secure enough
	- [x] Link “data classification examples” to:
		*  https://policy.security.harvard.edu/view-data-security-level
- Pop-up: The dataset [data file] should not be used in DP Creator
	- [x] Change “DPcreator” to “DP Creator”

**Comment by raprasad** [comment]
Looks good in the PR!
