### ISSUE TITLE
Epsilon Page Text Changes

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#456]
- Miro reference: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366776975305&cot=14
- Change page title. 
	- For future: move these questions to the “Validate Dataset” page
- Question “Is your data a secret and simple random sample from a larger population?”
	- [x] Typo in the information box, `instituions` should be `institutions`
	- [x] Add context -> if the data is a simple random sample, we can use methods (amplification) to increase the accuracy and utility of the statistics you create.
- Question 2: about dataset size being made public
     - [x] Add context: If the dataset size can be made public, less of the privacy budget is used when creating statistics

**Comment by raprasad** [comment]
# Tell Us More About Your Dataset
The questions below will help determine what algorithms to use when creating differentially private statistics from your file.

- Is your data a secret and simple random sample from a larger population?”
	- 	If the data is a simple random sample, we can use methods (amplification) to increase the accuracy and utility of the statistics you create.
* Can the number of observations in your dataset be made public?
	* If the dataset size can be made public, less of the privacy budget is used when creating statistics

**Comment by TaniaSchlatter** [comment]
We will need a brief page title to show at the top of the page in the step sequence.

**Comment by anniewu332** [comment]
Would "Set Noise Level" be accurate?

**Comment by Shoeboxam** [comment]
@rprasad: Looks good. This wording for question 2 may more clearly illustrate how this option influences the system:
- If the dataset size can be made public, we don't need to spend a portion of your privacy budget to estimate it.

@anniewu332: That is accurate. It would be helpful to add directionality like "add less noise", similar to the existing proposal. Regardless, I think accuracy is a better vehicle than noise level to illustrate the behavior.

**Comment by raprasad** [comment]
Thanks, @Shoeboxam

**Comment by ekraffmiller** [comment]
What is the decision for the new page title and wizard step name?  "Set Noise Level"? or "Set Accuracy Level"?

**Comment by anniewu332** [comment]
Let's use Set Accuracy Level.

**Comment by raprasad** [comment]
checked
