### ISSUE TITLE
Error messages on the Create Statistics pop up

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#458]
![image](https://user-images.githubusercontent.com/60662347/146072409-a72074d9-7b89-4d1c-9c9a-d8083fd60702.png)
![image](https://user-images.githubusercontent.com/60662347/146072435-f8c59aac-cf7c-4745-a47c-773d7551e4b2.png)

**Comment by raprasad** [comment]
checked
