### ISSUE TITLE
Release Page Text Changes

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#459]
- Miro reference: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366776693470&cot=14
- [x] Remove HTML download button
- [x] Remove XML download button
- Link “Check DP release in Dataverse”
	- [x] Link appropriately (back to the Dataset page or DV download file)
- Table with “DV Installation”, “Remaining time to complete release”, etc.
	- [x] Move this table after "DP Release Information" and before the accordion panels
	- [x] If the process is complete, remove the row "Remaining time to complete release"
	- ref: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457368233364946&cot=14
- [x] for support email at the bottom, use `info@opendp.org`

**Comment by raprasad** [comment]
reviewed
