### ISSUE TITLE
Text changes create statistics

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#460]
- Miro reference: https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366776975305&cot=14
- Delta box at top (blue/gray input box)
	- [x] Add tool tip - “reserved for future use”
- Warning box: “Changing the epsilon, delta…”
	- [x] Add link to the more info page
- Informational box: “You can apply differentially…”
	- [x] Remove box

**Comment by raprasad** [comment]
Checked
