### ISSUE TITLE
Release Page Formatting (HTML)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#463]
- Present JSON information in a tabular/HTML format
- [ ] Mock-up.  (background gray is `#ebebeb`)
- [ ] HTML implementation

- reference (last page): https://docs.google.com/document/d/1vY7qP23mmfL672l4BJr8m0k2pZ1DmCLF7tXI_CH0agg/edit

**Comment by raprasad** [comment]
Categories: show all of them for now, even if several hundred

**Comment by TaniaSchlatter** [comment]
Mockup docs reflecting changes discussed:

- Web app: [DP Release layout_web.pdf](https://github.com/opendp/dpcreator/files/7830915/DP.Release.layout_web.pdf)
- PDF format: [OpenDP_release_multipagePDF.pdf](https://github.com/opendp/dpcreator/files/7830913/OpenDP_release_multipagePDF.pdf)

Web:
<img width="927" alt="Screen Shot 2022-01-07 at 2 30 19 PM" src="https://user-images.githubusercontent.com/15386424/148597037-f3ef5c62-f711-40f2-ba00-aa4c87e3d0fe.png">

PDF:
<img width="954" alt="Screen Shot 2022-01-07 at 2 30 47 PM" src="https://user-images.githubusercontent.com/15386424/148597039-85902d01-e2a1-471b-9fdf-5eb3036911f6.png">

**Comment by raprasad** [comment]
Updates from 1/25 meeting:

- On initial load, keep the 1st parameter section open, close the other accordions
- Parameter spacing: 2-3 spaces after each value. (Same as 2-3 spaces after each label/value pair.)
- Histograms Result in the table
	-  Show the first “n” values (3 to 5 values?) and then have a link which expands the accordion.
- Histograms info within the Accordion.  (Can also try with (a)/(b) switched)
	- (a) Show result data and categories
	- (b) Show histogram figure/diagram
	- (c) Show parameters
