### ISSUE TITLE
Minor text updates

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#465]
### (1) "dataset" instead of "data file" (first two)
<img width="716" alt="Screen Shot 2022-01-05 at 2 51 12 PM" src="https://user-images.githubusercontent.com/1036060/148284694-62ad7c5d-8596-460c-a534-6710d60359fb.png">

**Comment by anniewu332** [comment]
Minor text updates needed as noted in the screenshots here: https://www.icloud.com/sharedalbum/#B0lJ058xyJ8FYcn  (Green color indicates the updates made to the DPCreatorText.csv today in the branch 465-textEditsMinor.

1/11 update: Please note the comments to the screenshots in the link above.

**Comment by raprasad** [comment]
Notes re: text changes
- Green text in album: updated in the CSV
- Buttons in title case
- Create ~~the~~ Statistics
- Create ~~Your~~ Statistic
- "(4) Generate DP **Release**" [add release]
