### ISSUE TITLE
Grey Continue button on the Confirm Variables page

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#468]
When returning to the Confirm Variables page from the Create Statistics page, after making a change, the Continue button stays grayed out.  Video of the steps taken:  https://harvard.zoom.us/rec/share/wdCU9-IG92e7hpo2LT_ifGKvHip3NfeWXRIdVOObsMWd_n0QF2btO5b3jhOFYVon.nNaiMoWlVjuERNxZ

**Comment by ekraffmiller** [comment]
I was able to recreate this by going to  the My Data page, then going back to Confirm Variables.  The variable min/max are saved as ints, but the Confirm Variables form expects them to be strings.  So when the page is refreshed when resuming the workflow, need to convert the min/max from int to string in order for the validation to work.
