### ISSUE TITLE
API Error after Submit Statistics

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#471]
Saw an API error message yesterday after I clicked on Submit Statistics.  See screenshot attached.  My Data page then showed the release status as In Execution.  
![4E2DB61E-C79A-4F4E-862E-1C36249A328A](https://user-images.githubusercontent.com/60662347/149013347-9f84ad39-0eff-44fc-816c-bc5d2d3bdb80.png)

**Comment by raprasad** [comment]
@ekraffmiller : This is a related ticket #445 - e.g. using the current error handling/catching, it may be possible to pull additional info out of the response

**Comment by raprasad** [comment]
Cannot reproduce

**Comment by raprasad** [comment]
closing for now
