### ISSUE TITLE
Running Epsilon Exceeds the Max Epsilon in the Create Statistic Popup Window

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#473]
In my Jan 12th test, Count generally worked, except when I got to the last variable on the list in the Create Statistics popup.   I got an error message saying the running epsilon exceeds the max epsilon by 0.00000000000000006.  

The instructions on the Create Statistics page (not the popup window) say that by default the total Epsilon will be distributed evenly between the statistics created, so I didn't expect to see the overage in the popup window.

<img width="378" alt="Screen Shot 2022-01-12 at 10 13 36 AM" src="https://user-images.githubusercontent.com/60662347/149358401-30722697-02c4-44b2-b0f6-f0f7f93771d3.png">

**Comment by raprasad** [comment]
fixed
