### ISSUE TITLE
Histograms (integer/float) with User Specified Bins

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#476]
Currently histograms work with categorical, boolean, and integer values (by binning on every value).

**tasks**
- [ ] map out data structures
- [ ] Plan UI changes / user input
- [ ] bin specification
  
---
- It may be easier to create a separate file, e.g. `dp_histogram_spec_integer.py` and addition additional logic here to check statistic + type: 
    - https://github.com/opendp/dpcreator/blob/develop/server/opendp_apps/analysis/validate_release_util.py#L453

**Comment by raprasad** [comment]
## Histogram Binning Options 
- All of these options assume that categories or ranges (min/max) are available. (No stability histograms yet)

### Input Option 1: Every value is used as a bin
- **Types**: String (categorical), Integer
   - Note: This is the only option for string—there is no additional user input

### Input Option 2: User enters # of bins
- **Types**: Integer, Float
- **UI**: 
	- Show the min/max as a reference (static, not part of input form)
- **Validation**: 
	- Check that the 0 < `# bins` <= `range of values`
		- e.g. This would fail: 
			- type: integer
			- number of bins: 10
			- min: 1; max: 5
- **Server side**: 
	- Separate into equal range bins
	- Create a list of edges. (See Input Option 3 re: Edge construction)

### Input Option 3: User enters the bins
- **Types**: Integer, Float
- **UI**: 
	- Show the min/max as a reference (static, not part of input form)
	- For the list entry, pre-fill with the min/max values 
		- Start with min on the left of box, max at right of box
	- Show entries as chips (similar to the confirm variables page input)
- **Validation**
	- deduplicate: no repeating numbers
	- numbers should be in ascending order; 
	- first bin >= min
	- last bin <= max
- **Edge construction**
	- OpenDP lib note, for specifying bin edges:
		- lower bound is included 
		- upper bound is excluded
	- Make sure that the edge values match the variable type. e.g. construct integer edges for type integer, float edges for type float, etc.
	- Only happens on the server side
	- first bin: [-infinity, 1st edge]
	- last bin: [last edge, infinity]
	- note: the 1st and last bin are constructed in the background—server side at validation and runtime.

**Comment by ekraffmiller** [comment]
Miro board containing mockup: https://miro.com/app/board/uXjVPf42J88=/?share_link_id=938635240471

**Comment by raprasad** [comment]
@raprasad API endpoint that returns edges and buckets

## Integers

**endpoint**:  `(.??..)/edges-buckets/integer`
**inputs**: all integers. `min`, `max`, `# of bins`
**output**: 
  - 401; invalid request + error message
  - 200: 
  ```json
  { "edges": [0, 20, 40],
    "buckets": [
        "[0, 19]", 
        "[20, 29]",
        "[20, 40]"
     ]
}
```
