### ISSUE TITLE
social auth for dev.dpcreator.org

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#481]
Main tasks:

- [x] Allow Vue to accept a Google Oauth ID via an environment variable
- [x] Create Google API key 
   - [x] Use info@opendp.org account
      - Allow localhost, dev.dpcreator.org, and demo.dpcreator.org
- [x] Configure azure k8s specs for deployment (@raprasad )
- [ ] ~~Add privacy policy page~~
---

- django-allauth: https://django-allauth.readthedocs.io/en/latest/providers.html#google
  - google oauth2 https://dev.to/mdrhmn/django-google-authentication-using-django-allauth-18f8
- method to load as encrypted file/fixture. (script + env variables)

**Comment by ekraffmiller** [comment]
The first task implemented here - https://github.com/opendp/dpcreator/tree/481-google-client

**Comment by ekraffmiller** [comment]
The OAuth 2.0 Client ID was created on the info@opendp.org account.  The form asked for a URL to our privacy policy and  terms of use.  So one more thing to do is to create a privacy policy page. (For now I just used the home page).  I added localhost and all our DP creator domains to the key, so it should be usable in local development and in all our deployments.

**Comment by raprasad** [comment]
## Websockets, allow setting of ws:// or wss:// -- the latter for SSL connections

In `client/src/store/dataset.js`, use the env settings for the websocket, e.g. VUE_APP_WEBSOCKET_PREFIX to replace.

Current:
  - ref: https://github.com/opendp/dpcreator/blob/481-google-client/client/src/store/dataset.js#L245
```javascript
        const prefix = 'ws://'
```

Future: 
```javascript
        // something like this or similar
        const prefix = this.vueSettings['VUE_APP_WEBSOCKET_PREFIX'],
```
---

### Update google client id in the SignUpForm


- Update to use the google client id from the API:
  - setting to change: https://github.com/opendp/dpcreator/blob/481-google-client/client/src/components/Accounts/SignUp/SignUpForm.vue#L232
 ```
   googleSignInParams: {
      client_id: process.env.VUE_APP_GOOGLE_CLIENT,
    },

 ```
  - update to new settings, e.g. `client_id: this.vueSettings['VUE_APP_GOOGLE_CLIENT_ID'],`
