### ISSUE TITLE
variableInfo not found with test dataset

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#503]
- Needs to be reproduced/diagnosed
- May be related to camelcase/etc.

**Comment by anniewu332** [comment]
[duck MOCK_DATA 5 vars no missing.csv](https://github.com/opendp/dpcreator/files/8061963/duck.MOCK_DATA.5.vars.no.missing.csv)
<img width="1096" alt="Screen Shot 2022-02-14 at 9 39 03 AM" src="https://user-images.githubusercontent.com/60662347/153894121-a020e00b-f9b5-4df3-a963-cb0d6d9983f2.png">
