### ISSUE TITLE
PDF: histogram table

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#506]
## Release page

1. Add a histogram "table" as well as the diagram. Table example: 

| eye color | count |
|-----------|-------|
| brown     | 562   |
| blue      | 127   |
| green     | 21    |

- The table could become unwieldy--e.g. 100s of rows
- Set a static variable, say `HISTOGRAM_DISPLAY_ROW_COUNT` for a row count limit. 
    - Set it to 40 rows (an arbitrary number).
- Example scenario:  `HISTOGRAM_DISPLAY_ROW_COUNT = 40` and there are `400` category/value pairs
   - (1) On the release page, show the histogram table with the first `40` bins and a message:
       - "The histogram has 400 bins. The first 40 are shown below. [View the full table of 400 bins](http://link-to-full-table-at-bottom-of-doc)".
   - (2) At the bottom of the release page, add an "additional info" section, which displays all 400 bins of the table.
   - (3) Add an in-page link from the message in (1) to all 400 rows in (2)

**Comment by ekraffmiller** [comment]
@raprasad,
- Is "remove general accuracy" listed above still needed? (since we did the Histogram accuracy fix?)
- I assume the release page fix is to remove fixed value for the stats that don't require it? Is there anything else to be fixed?
- What context should I add for negative numbers on the release page?

**Comment by raprasad** [comment]
@ekraffmiller (just rewrote the issue--it was dated)

**Comment by ekraffmiller** [comment]
@raprasad for the table, does it make sense to have the extra data in an accordion or some other expandable component, rather than an additional info section on the bottom? (I can see how the additional info section makes sense for the PDF)

**Comment by raprasad** [comment]
@ekraffmiller Agreed, an expandable component makes sense

**Comment by ekraffmiller** [comment]
@Raman  since the release page  is only  showing the PDF, we don't need an HTML  table. Let me know if you want me to work on the PDF  change for this  ticket.

**Comment by raprasad** [comment]
@ekraffmiller Yes, let's talk. I can show you where the PDF code is.

**Comment by raprasad** [comment]
Closing, duplicated in #649

**Comment by raprasad** [comment]
Closing for #649
