### ISSUE TITLE
Checkboxes on the Confirm Variables Page

### ISSUE THREAD

**Issue by anniewu332** [opendifferentialprivacy/opendp-ux#580]
On the Confirm Variables page, a user tends to think as soon as the min and max (or categories) are entered, they should be able to continue, which is not the case with the current app design.  The current design requires at least one checkbox for the variable to be checked before the Continue button can be clicked.  The user gets confused as to why they cannot continue after entering the min and the max.

We need some way to remind/force the user to check the checkboxes, e.g. visually distinguish selected/unselected variable lines depending on whether the checkboxes are checked.  

@ekraffmiller @TaniaSchlatter 

3/28/22 edit: screenshot attached per Tania's request:
<img width="789" alt="Screen Shot 2022-03-28 at 11 00 11 AM" src="https://user-images.githubusercontent.com/60662347/160427694-20a0217d-96b3-40be-9393-66cc6b06449a.png">

**Comment by TaniaSchlatter** [comment]
Instructional text:
![Screen Shot 2022-03-29 at 2 31 29 PM](https://user-images.githubusercontent.com/15386424/160682886-66470d06-da5a-42e8-8030-910125b09ac5.png)

**Comment by TaniaSchlatter** [comment]
There are several possible approaches to this issue. One or all could be implemented.
1. Edit the instructions at the top, and number them. State explicitly in step 1 to check the checkbox 
2. Add a dynamic counter above the table that says something like, "0 variables selected"
3. This dynamic counter could also be added at the bottom near the button 
4. Allow users to click the button, and display error feedback

**Comment by raprasad** [comment]
Improved. Additional UI elements added
