### ISSUE TITLE
Updates to the instructions

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#603]
This list is taken from the document: [Consolidated notes Open DP Tool HDV feedback](https://docs.google.com/document/d/1upepMCNk2dTmMt3SudEut40cMNZ9FkT5v4lCZX-cr44/edit0

---

Task: Update the tutorial instructions in this areas. Note, not all of the "new text" is given

- [x] Current instruction: "Under File Options dropdown, choose DP Creator."
  - This instruction was not clear. Hard to find even with instruction. Went to “Edit Files” in the file table and dataset. Suggest calling it the “kabob” menu with the three dots. 
- [x] Note to disable the pop-up blocker
  - Re-emphasize this in the instructions. 
- [x] Upon initial login, a user commented, "I'm suspicious because importing data went so well."
  - In the instructions note at which step the data file is moved to DP Creator--on the confirm variable page. Prior to that, only citation metadata is retrieved from Dataverse
- [x] Confirm variables page: Be clear that at least 1 variable must be selected
- [x] Confirm variables page, when entering categories, emphasize pressing return after entering each value
- [x] Update screenshots to show whole app interface and highlight the area to click on
- [x] Update the link on the home page of the DP Creator demo app to this DP Creator Beta Instructions doc (published version) https://docs.google.com/document/d/e/2PACX-1vRlZ2IgigIhl4oz_uOakQPxovzlrmFkbD-x_9RUO31dC0eRq2wCt_vN2Go0_9LTRd67srjgy04CfPVk/pub
- [x] Confirm Variables page: add the text on app page to the user instructions doc, and reconcile the text.

**Comment by anniewu332** [comment]
Items 1,2, 4, 5 were already in the user tutorial instructions doc.  

Let's use the instructions doc (after it has the updated screenshots ) instead of the quick start doc.   Added items 6 and 7 for this.

**Comment by anniewu332** [comment]
Added checklist item 8 based on discussions at the 5/3 2 PM.
