### ISSUE TITLE
Sampling Frame Page: population size

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#605]
question: "Is your data a secret and random sample..."
- [ ] Move this question below "Can the number of observations be made..."
- [ ] Population size input box: remove up/down areas from the input box
   - [ ] If the answer to ""Can the number of observations be made public...?" is "Yes":
      -  Validate that the population size is greater than the dataset size

**Comment by anniewu332** [comment]
This is not critical for the beta demo release.

**Comment by raprasad** [comment]
- Added dataset_size to the datasetinfo API result
