### ISSUE TITLE
force ssl when appropriate

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#607]
**Issue**
  - Currently, azure K8s deployments use cloudflare to provide https. 
  - However, users may still access the application via "http". 

**To do**
  - Force the `http` links to `https`.

**Note**:  The current access layers are:
  - **https:**  cloudflare -> nginx container -> django container
  - **http:** nginx container -> django container

Django contains settings such as [SECURE_SSL_REDIRECT](https://docs.djangoproject.com/en/4.0/ref/settings/#secure-ssl-redirect) and  [SECURE_PROXY_SSL_HEADER](https://docs.djangoproject.com/en/4.0/ref/settings/#secure-proxy-ssl-header). 

However, the change likely needs to happen at the **_cloudflare_** and/or **_nginx_** layer(s). 

---

- related to #606

**Comment by anniewu332** [comment]
Is this related to https://docs.google.com/document/d/1upepMCNk2dTmMt3SudEut40cMNZ9FkT5v4lCZX-cr44/edit#bookmark=id.hvf95of3ttmr ?

**Comment by raprasad** [comment]
Page Rule was missing in Cloudflare for demo.dpcreator. No coding changes needed
