### ISSUE TITLE
confirm variables: Type dropdown

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#608]
- Issue: The chosen type is not shown in the dropdown when trying to select another. 
  - For example, if the default is “Integer”, when the user clicks on the dropdown, “Integer” doesn’t appear–the chosen type is hidden
- Fix: When clicking on the dropdown, show all the dropdown choices, including the selected choice.

**Comment by anniewu332** [comment]
This is not critical for beta demo release.
