### ISSUE TITLE
PDF navigation improvement

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#609]
Currently the PDF navigation to move to the next page requires:
 - scrolling to the bottom of the PDF window (not the PDF itself)
 - hovering over the lower part of the PDF window to reveal the nav menu
 
 Fix: if part of the component, show a nav bar at the top of the PDF

**Comment by anniewu332** [comment]
This is not critical for beta demo release.

**Comment by raprasad** [comment]
(closed)
