### ISSUE TITLE
File upload, allow deletes from mydata page

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#640]
- Allow the user to delete a file upload or a Dataverse file(**)
- Needs discussion: allow delete regardless of the state of the workflow?
- [ ] API endpoint for delete
- [ ] UI connection

---
Added 7/11

**Notes**

- This workflow below is true for both **DataSetInfo** types (**DataverseFileInfo** and **UploadedFile**)  
- Since the application is in "test mode", we want to allow deletion of ReleaseInfo objects. However, that functionality should be restricted when in production**.
   - Add django setting `ALLOW_RELEASE_DELETION` with default as `True`
      - `ALLOW_RELEASE_DELETION is True` -> The endpoints deletes related **ReleaseInfo** objects
      - `ALLOW_RELEASE_DELETION is False` -> If related **ReleaseInfo** objects exist, the delete endpoint is forbidden, e.g. returns an error
      - **production - The production use case isn't fully fleshed out. As a result, the UI doesn't need to have knowledge of the `ALLOW_RELEASE_DELETION` setting and it is assumed to be `True`
         - Future placeholder issue: #661

**Basic Delete Flow**

- (1) Delete endpoint before AnalysisPlan exists
   - **Input**: 
     - **DataSetInfo**.object_id 
   - **Action**: Deletes the **DataSetInfo** object if it doesn't yet have related **AnalysisPlan** objects
     - If there is an **AnalysisPlan** object, return an error
- (2) Delete endpoint when DataSetInfo has an existing AnalysisPlan object (or objects)
  - **Inputs**:
     - **DataSetInfo**.object_id
     - **AnalysisPlan**.object_id 
  - **Action**:  
     - If the AnalysisPlan has a  related **ReleaseInfo** object
       - If `ALLOW_RELEASE_DELETION` is `False`, **return an error**
       - If `ALLOW_RELEASE_DELETION` is `True`, **delete the ReleaseInfo**
     - Delete the **AnalysisPlan** 
     - If there are no other **AnalysisPlan** objects, also delete the **DataSetInfo** object 
         - (_Currently this is always the case but will not be true once multiple releases may be created_)

**Comment by ecowan** [comment]
@raprasad @ekraffmiller A better way to handle the DatasetInfo delete is via a DELETE to /dataset-info/<object-id>, this is more in line with restful standards and expectations. Each individual AnalysisPlan would then be deleted via a DELETE to /analyze/<object-id>

Also, why delete the DatasetInfo object if there are no other AnalysisPlan objects? Is there a case where a user would want to delete an existing AnalysisPlan to start over, but leave the data in place?

**Comment by ekraffmiller** [comment]
> Also, why delete the DatasetInfo object if there are no other AnalysisPlan objects? Is there a case where a user would want to delete an existing AnalysisPlan to start over, but leave the data in place?

@ecowan I agree  that the user might want to do that, even though currently  the UI doesn't allow it. So it makes sense to  me that the API /analyze/ DELETE  wouldn't automatically delete the dataset info, but logic could exist in the UI to delete the datasetInfo separately if needed. @raprasad does that make sense?

**Comment by ecowan** [comment]
@raprasad @ekraffmiller Just pushed another update - the /dataset-info/ endpoint will delete all associated objects (ReleaseInfo, etc.) and the /analyze/ endpoint will delete associated ReleaseInfo objects if allowed, but will not delete the DatasetInfo object
