### ISSUE TITLE
Email server / notifications

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#65]
- reference for email notifications:
https://docs.google.com/spreadsheets/d/1OSvi8ge-pghkIzBgVKfafXxxXeBYpaDX0U8xIZZjuoc/edit#gid=0

**Comment by ecowan** [comment]
Azure doesn't have a builtin email service like AWS SES, it relies on 3rd party SMTP relay. This example uses SendGrid: https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email

**Comment by raprasad** [comment]
old, close for now
