### ISSUE TITLE
Delete button on My Data Details page throws error

### ISSUE THREAD

**Issue by ekraffmiller** [opendifferentialprivacy/opendp-ux#670]

**Comment by ecowan** [comment]
@ekraffmiller can you please write out the steps to reproduce this and what the error says / looks like?

**Comment by ekraffmiller** [comment]
@ecowan To reproduce, upload a file, click on the "View Details" link for the file, and on the Details page, click on the Delete button.  It will produce a runtime error with the stack trace on the page.
