### ISSUE TITLE
cloud deployment/hosting for OpenDP App

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#75]
- decide platform
- [x] azure credit information
---
- [x] docker images
  - [x] vue prod files
- [x] k8s basic spec
- [x] k8s / ingress / https / etc
- [x] existing code working w/o secrets
- [x] add nginx frontend
- [x] postgres image w/ persistent data 
- [x] env secrets

**Comment by ecowan** [comment]
Looks like the Azure app engine is an option: https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app

**Comment by raprasad** [comment]
- [x] csrf issues after login
  - https://docs.djangoproject.com/en/3.2/ref/csrf/#ajax

## 1st time
1. `dv-handoff` -> succeeds
1. `rest-auth/login` -> succeeds
1. `rest-auth/user` -> succeeds
1. `api/dv-user` -> fails with `{"detail":"CSRF Failed: CSRF token missing or incorrect."}`

## 2nd time (already logged in)
1. `dv-handoff` -> fails with `{"detail":"CSRF Failed: CSRF token missing or incorrect."}`
  - if you log out, it works like the 1st time ^

**Comment by raprasad** [comment]
^ Was a custom cookie issue....

**Comment by raprasad** [comment]
### serve nginx static files
- [x] django: STATIC_ROOT 
  - Dockerfile, set new DEFAULT_STATIC_ROOT
     - Have the same path for **npm build**
     - python manage.py collectstatic.  
       - Run npm before collectstatic to avoid overwrite...
- [x] nginx setup
  - [x] serve from new DEFAULT_STATIC_ROOT
  - [x] max upload size
  - [x] proxy to app

**Comment by raprasad** [comment]
- [x] merge dpcreator-deploy into dpcreator
- [x] add instructions into repo

**Comment by raprasad** [comment]
moving db link and https to new issue
