### ISSUE TITLE
DP Creator: External Text Review

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#89]
(update) This work is being tracked on the [OpenDP-content-inventory](https://docs.google.com/spreadsheets/d/1Yo4o_m9B9n74b5jAgVgDHT-XcYuorZ9JKvHuCmbnbUo/edit#gid=1839901367)

Most up to date content is in the [DPCreator Text spreadsheet](https://docs.google.com/spreadsheets/d/1cOKfTZvI_zxHaT_-aagDbg1fPsPyBuWRIM4YPh8QExs/edit#gid=2118957389)

 - [x] via Salil, update "Does each row contain only one individual?" to "Does each individual appear in only one row?"  (Additional from @Shoeboxam: "How many rows can each individual influence?")

**Comment by TaniaSchlatter** [comment]
Here is a [content inventory to track content](https://docs.google.com/spreadsheets/d/1Yo4o_m9B9n74b5jAgVgDHT-XcYuorZ9JKvHuCmbnbUo/edit#gid=1839901367) needed for the application. It includes links to existing draft content and/or notes. 

[Spreadsheet with content from the prototype, for review, updating, and populating the build](https://docs.google.com/spreadsheets/d/1cOKfTZvI_zxHaT_-aagDbg1fPsPyBuWRIM4YPh8QExs/edit#gid=2118957389)

**Comment by TaniaSchlatter** [comment]
We have draft content from the .pdf mockups from Agile Monkeys in the application, that has been copied into the DPCreator Text spreadsheet for editing. We need to review and complete content before launch. Here is a high-level proposed process:

- [x] merge content edited in the [spreadsheet](https://docs.google.com/spreadsheets/d/1cOKfTZvI_zxHaT_-aagDbg1fPsPyBuWRIM4YPh8QExs/edit#gid=2118957389)
- [ ] internal team, stakeholders [review content and comments on the Miro board](https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366452823836&cot=14). Frame or lense through which to consider what we have is anyone interested in trying the app, from Dataverse account creation through depositing a test file, to creating a DPCreator account and making a release. We acknowledge that DP education will not be complete, and evdn if complete requires links out of the DP Creator app. Make edits and complete _(timeframe?)_
- [ ] review with external stakeholders _(timeframe?)_
- [ ] revise and update again before launch _(timeframe?)_

**Comment by pdurbin** [comment]
I just created some Google Slides called "DP Creator text review" that contain screenshots (and my comments) as of 1dd39d1: https://docs.google.com/presentation/d/1tGOQyhjtSyO7CmbzFaCDetuEVk2Rbb6bPY_M90VLhNg/edit?usp=sharing

**Comment by TaniaSchlatter** [comment]
Note that the latest place to look for text and comments (including @pdurbin's) for review is [in Miro](https://miro.com/app/board/o9J_kj6tycQ=/?moveToWidget=3074457366452823836&cot=14).

**Comment by raprasad** [comment]
replaced by #419

**Comment by raprasad** [comment]
(additional text reviews underway. results of most recent were here: #515)
